config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :meetups
  devise_for :users
  root "users#index"
  post "/users/:id", to: "users#show"
  post "/users/:id/edit", to: "users#edit"
  resources :users do
    resources :endorsements
    resources :reports
  end

  resources :conversations do
    resources :messages
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_pic
  validates :first_name, :postcode, :dob, :gender, :ability, :goals, :profile_pic, presence: true

  def self.search(params)
    where("LOWER(first_name) LIKE :term OR LOWER(postcode) LIKE :term OR LOWER(gender) LIKE :term
      OR LOWER(ability) LIKE :term OR LOWER(goals) LIKE :term", term: "%#{params}%")
  end

  def self.unread_counter(current_user)
    unread_messages = 0
    conversations = Conversation.all
    conversations.each do |conversation|
      unless current_user.nil?
        if conversation.recipient_id == current_user.id || conversation.sender_id == current_user.id
          conversation.messages.each do |message|
            unless message.user_id == current_user.id
              if message.read.to_s == '0'
                unread_messages += 1
              end
            end
          end
        end
      end
    end
    unread_messages
  end


  has_many :endorsements

  has_many :reports

  has_many :meetups

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update ]

  def index
    @users = User.all
    if !params[:q].nil? && params[:q].downcase == "male"
      @male_users = []
      @users.each do |user|
        @male_users << user if user.gender == "Male"
      end
      @users = @male_users
    elsif params[:q] && !params[:q].empty? 
      @users = @users.search(params[:q].downcase) 
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_url
    else
      redirect_to new_user_registration_path
    end
  end

  def show
    @endorsements = Endorsement.all
    @endorsement = Endorsement.new
    @users = User.all
    @user = User.find(params[:id])

    @user_endorsements = push_user_endorsements(@endorsements, @user)
    @endorsement_counter = calculate_user_endorsements(@endorsements, @user)

    @reports = Report.all
    @reported = reported?(@reports, @user, current_user)
  end

  def edit
    @user = User.find(params[:id])
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

  def push_user_endorsements(endorsements, user)
    user_endorsements = []
    endorsements.each do |endorsement|
      user_endorsements << { user_id: endorsement.endorser_id, message: endorsement.body } if endorsement.user_id == user.id
    end
    user_endorsements
  end

  def calculate_user_endorsements(endorsements, user)
    counter = 0
    endorsements.each do |endorsement|
      counter+= 1 if endorsement.user_id == user.id
    end
    counter
  end

  def reported?(reports, reported_user, reporter_user)
    report_match = false
    reports.each do |report|
      report_match = true if report.user_id == reported_user.id && report.reporter_id == reporter_user.id
    end
    report_match
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/users/_form.html.erb
<%= stylesheet_link_tag "users", :media => "screen" %>

<%= form_for([@user, @endorsement]) do |f| %>
  <%= f.text_field :body, placeholder: 'Make an endorsement..', class: "input_message_form" %>   
  <%= f.text_field :user_id, value: @user.id, type: "hidden" %> 
  <%= f.text_field :endorser_id, value: current_user.id, type: "hidden" %> 
  <%= f.submit "👍", class: "thumbs-up" %>
<% end %>

app/views/users/index.html.erb
<body>
    <%= stylesheet_link_tag "home_page", :media => "screen" %>
      <% if user_signed_in? %>
        <div class="background">
          <div class="wrap">
          <br>
          <br>
          <%= form_tag("/users", method: 'get') do %>
             <%= text_field_tag :q, "", class: 'search_box', placeholder: "Find running buddy" %>
             <%= submit_tag"🔍", class: "magnifying_glass" %>
          <% end %>
          </div>
          <% @users.each do |user| %>
            <div class="user-container">
              <% if user.profile_pic.attached? %>
                <% image = user.profile_pic %>
              <% else %>
                <% image = 'default.jpg' %>
              <% end %>
              <%= image_tag(image, class: "profile_pic") %>
              <div class ="user-details">
                <p><strong> Name: </strong> <%= user.first_name %></p>
                <p><strong> Area:</strong> <%= user.postcode %></p>
                <p><strong> Gender: </strong> <%= user.gender %></p>
                <p><strong> Ability: </strong> <%= user.ability %></p>
                <p><strong> Goals: </strong> <%= user.goals %></p>
              </div>

              <% if user == current_user %>
                <%= button_to "View Your Profile", user, class: "user_home_button" %>
              <% else %>
                <%= button_to "View #{user.first_name}'s Profile", user, class: "user_home_button" %>
              <% end %>
            </div>
          <% end %>
        </div>
      <% else %>
      <div class="landing_page_background">
        <div class="landing_page_content">
          <%= image_tag "pace-landing-logo.png", class: "landing_page_logo"%>
          <div class="slogan"> <p> Feel safer, train harder </p> </div>
          <span class='button_loggedout'>
            <%= link_to "Login", new_user_session_path %>
          </span>
          </br>
          <span class='button_loggedout'>
            <%= link_to "Sign up", new_user_registration_path %>
          </span>
        </div>
      </div>
    <% end %>
    <br>
</body>

app/views/users/show.html.erb
<%= stylesheet_link_tag "users", :media => "screen" %>

<div class="profile-body">
  <div class="user-container-profile">
    <% if @reported %>
      <p> You have reported this user! Our admin team is looking into this. </p>
    <% end %>

    <% if @user.profile_pic.attached? %>
      <% image = @user.profile_pic %>
    <% else %>
      <% image = 'default.jpg' %>
    <% end %>
    <%= image_tag(image, class: "profile_pic") %> <br />

    <p><strong> Name: </strong> <%= @user.first_name %></p>
    <p><strong> Area:</strong> <%= @user.postcode %></p>
    <p><strong> Gender: </strong> <%= @user.gender %></p>
    <p><strong> Ability: </strong> <%= @user.ability %></p>
    <p><strong> Goals: </strong> <%= @user.goals %></p>

    <br>
    <% if current_user.id == @user.id %>
      <p><%= @user.email %></p>
      <%= link_to "Edit", edit_user_registration_path %>
    <% else %>
      <div class="message_user_bubble"> 
        <%= link_to "Message this user", conversations_path(sender_id: current_user.id, recipient_id: @user.id), method: "post"%>
      </div>

      <div class="report_user_bubble">
        <%= link_to "Report this user", new_user_report_path(user_id: @user.id) %>
      </div>
      <%= render 'form', endorsement: @endorsement %>
    <% end %>
    </div> 
    <% if current_user.id != @user.id %>
      <% if !@user_endorsements.empty? %>
      <div class="user-endorsements-container">
      <% unless @endorsement_counter == 0 %>
        Endorsed by 👍 <%= @endorsement_counter %>
      <% end %>
      <br>
      <% @user_endorsements.each do |endorsement| %>
        <% user_name = '' %>
      <% @users.each do |user| %>
        <% user_name = user.first_name if user.id == endorsement[:user_id] %> 
      <% end %>
      <br>
        <% if endorsement[:message] == '' %>
          <i><%= user_name %></i>
        <br>
        <% else %>
          <i><%= user_name %></i> 🗣 <%= endorsement[:message] %> 
        <br>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
</div>