config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :meetups
  devise_for :users
  root "users#index"
  post "/users/:id", to: "users#show"
  post "/users/:id/edit", to: "users#edit"
  resources :users do
    resources :endorsements
    resources :reports
  end

  resources :conversations do
    resources :messages
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/endorsement.rb
class Endorsement < ApplicationRecord
  belongs_to :user
end

app/controllers/endorsements_controller.rb
class EndorsementsController < ApplicationController
  def new
    @endorsement = Endorsement.new
    @user = User.find(params[:user_id])
  end

  def create
    @endorsement = Endorsement.create(endorsement_params)
    redirect_to "/users/#{params[:user_id]}"
  end

  def show
    @endorsement = Endorsement.new
  end

  private

  def endorsement_params
    params.require(:endorsement).permit(:body, :user_id, :endorser_id)
  end
end

app/helpers/endorsements_helper.rb
module EndorsementsHelper
end

app/views/endorsements/new.html.erb
<h1> Endorse a user </h1>

<div class="input_message_form">
  <%= form_for @endorsement, url: user_endorsements_path do |f| %>
    <%= f.text_area :body, class: "message_area"%>
    <%= f.text_field :user_id, value: @user.id, type: "hidden" %> <br />
    <%= f.text_field :endorser_id, value: current_user.id, type: "hidden" %> <br />
    <%= f.submit "👍" %>
  <% end %>
</div>