config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :meetups
  devise_for :users
  root "users#index"
  post "/users/:id", to: "users#show"
  post "/users/:id/edit", to: "users#edit"
  resources :users do
    resources :endorsements
    resources :reports
  end

  resources :conversations do
    resources :messages
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :user
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController

  def new
    @report = Report.new
    @user = User.find(params[:user_id])
  end

  def create
    @report = Report.create(report_params)
    redirect_to "/users/#{params[:user_id]}"
  end

  private

  def report_params
    params.require(:report).permit(:body, :user_id, :reporter_id)
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/new.html.erb
<%= stylesheet_link_tag "reports_page", :media => "screen" %>
<div class="reports-body">
  <h1> Report a user </h1>

  Please give your reasons for reporting this user.

  <div class="input_message_form">
    <%= form_for @report, url: user_reports_path do |f| %>
      <%= f.text_area :body, class: "report_message_area"%>
      <%= f.text_field :user_id, value: @user.id, type: "hidden" %> <br />
      <%= f.text_field :reporter_id, value: current_user.id, type: "hidden" %> <br />
      <%= f.submit "Confirm report", class: "send_report_button" %>
    <% end %>
  </div>
</div>