config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :meetups
  devise_for :users
  root "users#index"
  post "/users/:id", to: "users#show"
  post "/users/:id/edit", to: "users#edit"
  resources :users do
    resources :endorsements
    resources :reports
  end

  resources :conversations do
    resources :messages
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navbar.html.erb
<header>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <% if user_signed_in? %>
    <div class="header-container">
      <a href="/"><%= image_tag "pace-logo.png", class: "pace-logo"%></a>
      <nav>
          <ul>
            <div class="top2b">
                <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
                <li><%= link_to('View profile', current_user) %></li>
                <% if User.unread_counter(current_user).nil? || User.unread_counter(current_user) == 0 %>
                  <li><%= link_to("View inbox", conversations_path) %></li>
                <% else %>
                  <li><b><%= link_to("View inbox (#{User.unread_counter(current_user)})", conversations_path) %></b></li>
                <% end %>
                <li><%= link_to("Plan a meetup", meetups_path) %></li>      
            </div>
            <div id="topmenu" onclick="drop2(event)">
              <div class="bar1"></div>
              <div class="bar2"></div>
              <div class="bar3"></div>
            </div>
            <div id="menu2" onclick="hide2()">
              <ul>
                <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
                <li><%= link_to('View profile', current_user) %></li>
                <% if User.unread_counter(current_user).nil? || User.unread_counter(current_user) == 0 %>
                  <li><%= link_to("View inbox", conversations_path) %></li>
                <% else %>
                  <li><b><%= link_to("View inbox (#{User.unread_counter(current_user)})", conversations_path) %></b></li>
                <% end %>
                <li><%= link_to("Plan a meetup", meetups_path) %></li>
              </ul>
            </div>
          </ul>
      </nav>
    </div>
  <% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pace</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

  </head>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <body>
    <%= render "layouts/navbar" %>
    <%= yield %>
  </body>

  <div class="footer">
    <p>@2021-team-speedy</p>
  </div>
  
</html>